# -*- coding: utf-8 -*-
"""VolleyballMonster.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NIF_5iApBOX2aNV4UWrDyFU2m5quR3gS
"""

from google.colab import files
uploaded = files.upload()

!unzip -q *.zip
print("What the file has:")
!ls -la

!find /content -name "data.yaml" 2>/dev/null

import yaml


with open("/content/data.yaml", "r") as f:
    data = yaml.safe_load(f)

data['train'] = '/content/train/images'
data['val'] = '/content/train/images'

with open("/content/data_train_only.yaml", "w") as f:
    yaml.dump(data, f)

print("Data Yaml is edited")

!pip install ultralytics -q
from ultralytics import YOLO

model = YOLO("yolov8n.pt")


model.train(data="/content/data_train_only.yaml", epochs=40, imgsz=640, batch=16, patience=10)

from ultralytics import YOLO
import glob
from google.colab import files


model = YOLO("runs/detect/train5/weights/best.pt")


results = model.predict(
    source=video_name,
    save=True,
    conf=0.10,
    iou = 0.45,
    stream=True,
    show=True,
    line_width=4,
    project="runs/detect",
    name="final_demo",
    exist_ok=True
)

for _ in results:
    pass


final_video = glob.glob("runs/detect/final_demo/*.mp4")[0]

print("Video Downloaded:", final_video)
files.download(final_video)